### ISSUE TITLE
BUG: while commenting on a squad post, the comment box does not get empty after comment

### ISSUE THREAD

**Issue by msamgan** [dailydotdev/apps#2099]
while commenting on a squad post, the comment box does not get empty after the comment. Even though the comment is posted as the comment is added to the end of the existing comments it feels like nothing happened.

https://github.com/dailydotdev/apps/assets/29948727/13ee87ae-e58b-4ad8-a053-c5ffca6b2517

**Comment by luisfilipegoncalves** [comment]
Might be related to this https://github.com/dailydotdev/daily/issues/965

**Comment by rebelchris** [comment]
Hi @luisfilipegoncalves thanks for noting this down.
This issue has been fixed in our latest release

**Comment by anirbanpaulin** [comment]
@rebelchris I'm sorry to inform you that the issue still persists in the extensions. Additionally, there is a new issue that you can check out at [dailydotdev/apps/issues/2132](https://github.com/dailydotdev/apps/issues/2132).
